sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "nightly"

cache: pip

install:
  - pip install cryptography<1.9
  - pip install .
  - pip install tox-travis
  - pip install pytest
  - pip install httmock
  - pip install coverage
  - pip install coveralls
  - pip install flake8==2.6.2
  - pip install flake8-import-order==0.8
  - pip install check-manifest

before_script:
  - "check-manifest"
  - "flake8 pycounter"

script:
  - tox

after_success:
  - coveralls
  - coverage report -m

notifications:
  irc: "chat.freenode.net#pycounter"

deploy:
  provider: pypi
  user: Wooble
  password:
    secure: hCCjmC5IU/Ch5Ux1WpOwnI5/veifCQ4uTs7z6HL7tQaaFkLArGlTSKuAGTs8P753PlxJwTiLvjYRkjHt0Tzav6GoZ3TkU4/QHnd6JZLhOth9uTj7ENgW3kWJ1zwZU9acLqDub1jqXglJVUWk6Ave1UMkNLFfhSnLW+v4x8m94Ww=
  on:
    tags: true
    python: 3.6
  distributions: "sdist bdist_wheel"
