sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
  - "nightly"

install:
  - pip install .
  - pip install git+https://github.com/PyCQA/pep8.git
  - pip install httmock
  - pip install coveralls
  - pip install flake8

before_script:
  - "flake8 pycounter"

script:
  coverage run setup.py test

after_success:
  coveralls

notifications:
  irc: "chat.freenode.net#pycounter"

matrix:
  allow_failures:
    - python: pypy3
    - python: nightly
