sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"

install:
  - pip install .
  - pip install httmock
  - pip install coveralls

script:
  coverage run setup.py test

after_success:
  coveralls
